### ISSUE TITLE
Request to Export createVerifyTokenCallback for Reusability in Other Projects

### ISSUE THREAD

**Issue by kauandotnet** [conceptadev/nestjs-modules#123]
Hello,

I am using this project and noticed that the createVerifyTokenCallback function is quite useful and could be reused in other projects.

Would it be possible to export this function so it can be directly imported?

Here's the function I'm referring to:

https://github.com/conceptadev/rockets/blob/4dd5a48af601508d1766f3d1969aef406a82d355/packages/nestjs-auth-refresh/src/utils/create-verify-token-callback.util.ts#L1-L15

**Comment by MrMaz** [comment]
@kauandotnet thanks for this request. i am assigning to myself and will start working on it today.

**Comment by MrMaz** [comment]
@kauandotnet please lmk if this PR gives you everything you need.

**Comment by kauandotnet** [comment]
@MrMaz  Yes, it does. Exporting `createVerifyAccessTokenCallback` and `createVerifyRefreshTokenCallback` will allow me to use them for my use case directly from the library. 

Thank you.
