### ISSUE TITLE
Bug: Original Error Not Sent to Sentry in AwsStorageException

### ISSUE THREAD

**Issue by tnramalho** [conceptadev/nestjs-modules#292]
When throwing the following exception:

```ts
throw new AwsStorageException({
  safeMessage: 'Error downloading file from S3',
  originalError: error,
});

```
Only the text 'Error downloading file from S3' appears in Sentry. It seems that the originalError is not being sent to Sentry for better traceability.

Expected Behavior
Both the safeMessage and the originalError should be captured and logged in Sentry, ensuring that the original error information is available for debugging.

Actual Behavior
Currently, only the safeMessage ('Error downloading file from S3') is showing up in Sentry, with no trace of the originalError information.

Steps to Reproduce

Add global exception filter

```typescript
import { ExceptionsFilter } from '@concepta/nestjs-exception';

// ... 
const exceptionsFilter = app.get(HttpAdapterHost);
 app.useGlobalFilters(new ExceptionsFilter(exceptionsFilter));

```
Register `LoggeModule` and `LoggerSentryModule`
make sure to use proper Sentry configurations

```typescript
// ... 
 LoggerSentryModule.forRoot({}),
    LoggerModule.forRootAsync({
      inject: [LoggerSentryTransport],
      useFactory: (
        loggerSentryTransport: LoggerSentryTransport,
      ) => {
        return {
          transports: [loggerSentryTransport],
        };
      },
    }),
```
Create the custom AwsStorageException class:

```ts
import {
  RuntimeException,
  RuntimeExceptionContext,
  RuntimeExceptionOptions,
} from '@concepta/nestjs-exception';

export class AwsStorageException extends RuntimeException {
  context: RuntimeExceptionContext;

  constructor(options: RuntimeExceptionOptions) {
    super(options);
    this.errorCode = 'AWS_STORAGE_ERROR';
  }
}
```
Trigger the exception with the following code snippet:

```ts
throw new AwsStorageException({
  safeMessage: 'Error downloading file from S3',
  originalError: error,
});
```
Check the Sentry logs for the captured exception.

Observe that only the safeMessage is logged, with no trace of the originalError.

Additional Information
Version: 5.0.0-alpha.4

**Comment by MrMaz** [comment]
Please add this feature to the logger and sentry logger modules and validate agains the scenario reported.

**Comment by MrMaz** [comment]
Fixed by https://github.com/conceptadev/rockets/pull/293
