### ISSUE TITLE
Tests are failing using node version v14.15.4

### ISSUE THREAD

**Issue by tnramalho** [conceptadev/nestjs-modules#55]
When running `yarn test ` using node version v14.15.4 we get 6 tests failing with 
` TypeError: (0 , crypto_1.randomUUID) is not a function` error,

however when running tests with v16.13.2 all tests passes.

should we either support v14.15.4 or add some documentation about the correct version to be used?

**Comment by MrMaz** [comment]
We actually need to require 18 now due to some dependencies. If this is a problem, we may provide some back compat.
